

### USER CREATE
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "phil",
  "email": "phil@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "phil@test.com",
  "password": "password"
}

### Favorites create
POST http://localhost:3000/favorite_hikes.json
Content-Type: application/json

{
  "hike_id": 5,
  "user_id": 1
}

### Favorites destroy
DELETE http://localhost:3000/favorite_hikes/4.json